name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
      - name: Build application
        run: npm run serve

      # - name: Deploy to remote server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no user@remote-server "cd /path/to/app && git pull && npm install && npm run build && pm2 restart app"
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
